blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    # ex: /blog/
    url(r'^$', views.index, name='index'),
    # ex: /blog/5/
    url(r'^(?P<blog_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /blog/5/results/
    url(r'^(?P<blog_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /blog/5/vote/
    url(r'^(?P<blog_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

myprj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from todo import views
#from django.views.generic import TemplateView
#from django.conf import settings
from todo import urls as todo_urls
from home import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^(?P<filename>(robots.txt)|(humans.txt))$',
        views.home_files, name='home-files'),
    #url(r'^home', views.home_page, name='home'),
    url(r'^todo/', include(todo_urls)),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^accounts/', include('allauth.urls')),
]

todo/urls.py
from django.conf.urls import url

from todo import views

urlpatterns = [
    url(r'^new$', views.new_todo, name='new_todo'),
    url(r'^(\d+)/$', views.view_todo, name='view_todo'),
    url(r'^(\d+)/add_item$', views.add_item, name='add_item'),
]

blog/models.py
# -*- coding: utf-8 -*-
""" models of blog app
"""
from django.db import models

# Create your models here.
import datetime
from django.utils import timezone
from tinymce.models import HTMLField

class Category(models.Model):
    """ Category in admin page
    """
    name = models.CharField(max_length=100, verbose_name='name')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='slug')

    description = models.TextField(max_length=4096)

    views_count = models.IntegerField(default=0, verbose_name='views count')

    def __unicode__(self):
        return self.name

class Tag(models.Model):
    """ tags in admin page
    """
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, verbose_name='slug')

    views_count = models.IntegerField(default=0)

    def __unicode__(self):
        return self.name

class Article(models.Model):
    """ articles in admin page
    """
    DRAFT = 'D'
    PUBLISHED = 'P'
    EXPIRED = 'E'
    ARTICLE_STATUS = (
        (DRAFT, 'Not Reviewed'),
        (PUBLISHED, 'Published'),
        (EXPIRED, 'Expired'),
    )


    def was_published_recently(self):
        """ field in admin page
        """
        return self.publish_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'publish_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, verbose_name='slug')

    status = models.CharField(max_length=1, choices=ARTICLE_STATUS, default=DRAFT)
    enable_comment = models.BooleanField(default=True)
    content = models.TextField()

    category = models.ForeignKey(Category, verbose_name="the related category")
    tags = models.ManyToManyField(Tag, verbose_name="the related tags", blank=True)

    publish_date = models.DateTimeField(auto_now=False, help_text="Please use the following format: <em>YYYY-MM-DD</em>.")

    created_date = models.DateTimeField(auto_now_add=False)

    views_count = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title

home/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class List(models.Model):
    def get_absolute_url(self):
        return reverse('view_todo', args=[self.id])

class Item(models.Model):
    # pass
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from .models import Article
from django.template import RequestContext, loader
from django.shortcuts import get_object_or_404


def index0(request):
    return HttpResponse("Hello, world. You're at the polls index.")

def detail0(request, blog_id):
    return HttpResponse("You're looking at article %s." % blog_id)

def results(request, blog_id):
    response = "You're looking at the results of article %s."
    return HttpResponse(response % blog_id)

def vote(request, blog_id):
    return HttpResponse("You're voting on article %s." % blog_id)

def index1(request):
    latest_blog_list = Article.objects.order_by('-publish_date')[:5]
    output = ', '.join([p.title for p in latest_blog_list])
    return HttpResponse(output)

def index2(request):
    latest_blog_list = Article.objects.order_by('-publish_date')[:15]
    template = loader.get_template('blog/index.html')
    context = RequestContext(request, {
        'latest_blog_list': latest_blog_list,
    })
    return HttpResponse(template.render(context))

def index(request):
    latest_blog_list = Article.objects.order_by('-publish_date')[:10]
    context = {'latest_blog_list': latest_blog_list}
    return render(request, 'blog/index.html', context)

def detail1(request, blog_id):
    try:
        item = Article.objects.get(pk=blog_id)
    except Article.DoesNotExist:
        raise Http404("Article does not exist")
    return render(request, 'blog/detail.html', {'item': item})

def detail(request, blog_id):
    item = get_object_or_404(Article, pk=blog_id)
    return render(request, 'blog/detail.html', {'item': item})


# Create your views here.

home/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request,'home/index.html', {})
def home_files(request, filename):
    return render(request, filename, {}, content_type="text/plain")

todo/views.py
from django.shortcuts import render, redirect
# from django.http import HttpResponse
from todo.models import Item, List

# Create your views here.
def home_page(request):
#    return HttpResponse('<html><title>Welcome to Django. This is my cool Site!</title></html>')
    return render(request, 'index.html')

def index(request):
    return render(request, 'index.html')

def view_todo(request, list_id):
    list_ = List.objects.get(id=list_id)
    return render(request, 'todo.html', {'list':list_})

def new_todo(request):
    list_ = List.objects.create()
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect('/todo/%d/' % (list_.id,))

def add_item(request, list_id):
    list_ = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect('/todo/%d/' % (list_.id,))

blog/templates/blog/detail.html
<h1>{{ item.title }}</h1>
<div>{{ item.content }}</div>

blog/templates/blog/index.html
{% load staticfiles %}
<img src="{% static "blog/bg.jpg" %}" alt="My image"/>

<link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}" />

<h1>Dmytro Blog Latest publications</h1>
{% if latest_blog_list %}
    <ul>
    {% for item in latest_blog_list %}
        <li><a href="{% url 'blog:detail' item.id %}">{{ item.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No items are available.</p>
{% endif %}

templates/base.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        <title>{% block head_title %} DMYTRO SITE | {% endblock %}</title>

        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">

        <link rel="stylesheet" href="{% static "css/normalize.min.css" %}">
        <link rel="stylesheet" href="{% static "css/main.css" %}">

        <script src="{% static "js/vendor/modernizr-2.8.3.min.js" %}"></script>
        {% block head_css %}{% endblock %}
        {% block head_javascript %}{% endblock %}
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        {% block navbar %}
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

            </nav>
        {% endblock %}


        {% block page %}
            <div class="container">
                {% block content %}

                {% endblock %}

                {% block sidebar %}


                    {% block recent %}

                    {% endblock %}

                {% endblock %}

            </div>
        {% endblock %}

        {% block footer %}
            <footer>
                {% block copyright %}
                {% endblock %}
            </footer>
        {% endblock %}

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="{% static "js/vendor/jquery-1.11.2.min.js" %}"><\/script>')</script>

        <script src="{% static "js/plugins.js" %}"></script>
        <script src="{% static "js/main.js" %}"></script>

        {% block footer_javascript %}{% endblock %}

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
    </body>
</html>

templates/blog/detail.html
<h1>{{ item.title }}</h1>
<div>{{ item.content }}</div>

templates/blog/index.html
{% extends "base.html" %}

{% load staticfiles %}
{% load listlastnews %} <!-- загрузить listlastnews тег -->
{% block head_title %} {{ block.super }} Dmytro Blog {% endblock %}

<link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}" />

{% block sidebar %}
    <style type="text/css">
        #sidebar { float: right; border: 1px dotted #ccc; padding: 4px; }
    </style>

    <div id="sidebar">
     {% lastnews %}

    </div>
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <h1>Janus Blog Latest publications</h1>
    </div>

            {% if latest_blog_list %}
                <ul>
                {% for item in latest_blog_list %}
                    <li><a href="{% url 'blog:detail' item.id %}">{{ item.title }}</a></li>
                {% endfor %}
                </ul>
            {% else %}
                <p>No items are available.</p>
            {% endif %}


{% endblock %} 

templates/blog/lastnews.html
<div id = "news">
<h4>Последние статьи</h4>
<ul class="links">
	{% for item in last5news %}

       <li><a href="{% url 'blog:detail' item.id %}">{{ item.title }}</a></li>
    {% endfor %}

</ul>
</div> 

templates/home/index.html
{% extends "base.html" %}

{% load staticfiles %}

{% block head_title %} {{ block.super }}  Dmytro HOME PAGE  {% endblock %}


{% block content %}

    <div class="jumbotron">
        <h1>Dmytro Home Page</h1>
    </div>

    <div class="container">



    </div>

{% endblock %}

todo/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Сделай сам To-Do lists</title>
    </head>
    <body>
        <h1>Сделай сам - Your To-Do list</h1>
        <form method="POST"  action="/todo/new">{% csrf_token %}
        <input name="item_text" id="id_new_item" placeholder="Добавить в список дел" />
        </form>
    </body>
</html>

todo/templates/todo.html
<html>
    <head>
        <title>Сделай сам To-Do lists</title>
    </head>
    <body>
        <h1>Сделай сам - Your To-Do list</h1>
        <form method="POST" action="/todo/{{ list.id }}/add_item">{% csrf_token %}
        <input name="item_text" id="id_new_item" placeholder="Добавить в список дел" />
        </form>
        <table id="id_list_table">


            {% for item in list.item_set.all %}

                <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
            {% endfor %}

        </table>
    </body>
</html>